import java.lang.*;
class Catch
{
  public static void main(String args[])
  {
    try
    {
      int a[]=new int[5];
      System.out.println(a[10]);
     }
     catch(ArithmeticException d)
     {
       System.out.println("Arithmetic Exception");
      }
      catch(ArrayIndexOutOfBoundsException abc)
      {
        System.out.println(abc);
       }
       catch(Exception e)
       {
         System.out.println(e);
        }
      }
    }        


OUTPUT:-

java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 5
